# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2725debf94a9754664c4d2fa6756bc6d1f787e51dcc6ad92ff7d7f66f1872f697a12d74ee841b55a9ddff01d4633688b5a01de25089b226f2c64dec6578614

test:
  secret_key_base: 015643113004ae9d5a94d24e842aa05aa54dd7f037fdfa27846b9776169b0fb78b5a9d366acae2f985b78443cca6d6bc3d15c6c067aac8f40b4d03f90b29dc60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
